### ISSUE TITLE
Function missing from jar

### ISSUE THREAD

**Issue by WACMemphis** [eemi2010/gwt-tour#19]
The class `com.ait.toolkit.core.client.Function` seems to be missing from the jar file located at ahome.

Or maybe I'm missing something here?

**Comment by eemi2010** [comment]
If you are using Maven. The library should get pull automatically. Otherwise you can download it from here https://oss.sonatype.org/content/repositories/snapshots/com/ahome-it/ahome-core/ and add it to your classpath.
